package com.dylibso.wasm.opa;

import com.dylibso.chicory.runtime.Instance;
import com.dylibso.chicory.runtime.Memory;

import java.util.Map;

// this file should be generated by chicory-bindgen
public interface OpaImports {
    Memory memory();

    void opaPrintln(Instance instance, int ptr);

    void opaAbort(Instance instance, int ptr);

    void initializeBuiltins(Map<String, Integer> mappings);

    int opaBuiltin0(Instance instance, int builtinId, int ctx);

    int opaBuiltin1(Instance instance, int builtinId, int ctx, int _1);

    int opaBuiltin2(Instance instance, int builtinId, int ctx, int _1, int _2);

    int opaBuiltin3(Instance instance, int builtinId, int ctx, int _1, int _2, int _3);

    int opaBuiltin4(Instance instance, int builtinId, int ctx, int _1, int _2, int _3, int _4);
}
