package com.dylibso.wasm.opa;

import com.dylibso.chicory.runtime.Memory;
import java.util.Map;

// this file should be generated by chicory-bindgen
public interface OpaImports {
    Memory memory();

    void opaPrintln(OpaWasm instance, int ptr);

    void opaAbort(OpaWasm instance, int ptr);

    void initializeBuiltins(Map<String, Integer> mappings);

    int opaBuiltin0(OpaWasm instance, int builtinId, int ctx);

    int opaBuiltin1(OpaWasm instance, int builtinId, int ctx, int _1);

    int opaBuiltin2(OpaWasm instance, int builtinId, int ctx, int _1, int _2);

    int opaBuiltin3(OpaWasm instance, int builtinId, int ctx, int _1, int _2, int _3);

    int opaBuiltin4(OpaWasm instance, int builtinId, int ctx, int _1, int _2, int _3, int _4);
}
